Traceback (most recent call last):
  File "server.py", line 3, in <module>
    from flask import Flask, request
ImportError: No module named flask
 * Serving Flask app 'server' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://localhost:8000 (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 636-277-877
Traceback (most recent call last):
  File "/Users/silviuh1/WORKSPACE/DEV/FACULTATE/licenta/Recommendation-Engine/job-recommendation-engine/server.py", line 41, in <module>
    app.run(host="localhost", port=8000, debug=True)
  File "/Users/silviuh1/PycharmProjects/job-recommendation-engine/venv/lib/python3.8/site-packages/flask/app.py", line 920, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/Users/silviuh1/PycharmProjects/job-recommendation-engine/venv/lib/python3.8/site-packages/werkzeug/serving.py", line 1083, in run_simple
    run_with_reloader(
  File "/Users/silviuh1/PycharmProjects/job-recommendation-engine/venv/lib/python3.8/site-packages/werkzeug/_reloader.py", line 434, in run_with_reloader
    ensure_echo_on()
  File "/Users/silviuh1/PycharmProjects/job-recommendation-engine/venv/lib/python3.8/site-packages/werkzeug/_reloader.py", line 414, in ensure_echo_on
    termios.tcsetattr(sys.stdin, termios.TCSANOW, attributes)
termios.error: (4, 'Interrupted system call')
